name: APK Oluştur

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Projeyi İndir
        uses: actions/checkout@v4

      - name: JDK 17 Kur
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: APK Oluştur
        run: |
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          if [ -z "$GRADLEW_PATH" ]; then
            echo "HATA: gradlew dosyası bulunamadı!"
            exit 1
          fi
          PROJECT_DIR=$(dirname "$GRADLEW_PATH")
          echo "Bulunan proje dizini: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: APK Yükle
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "**/app/build/outputs/apk/debug/app-debug.apk"
